### ISSUE TITLE
Needed to symlink lib -> gmusicgo/lib

### ISSUE THREAD

**Issue by abourget** [aleics/gmusicgo#1]
Otherwise, `go get` would fail.  I think there are refs to `github.com/aleics/gmusicgo/lib` directly.. although the `lib/` path is under `gmusicgo/` subdir (in addition to the repo name).

**Comment by aleics** [comment]
Hi! Sorry for the delay of my response. 
I've changed the structure of the folders. Now `github.com/aleics/gmusicgo/lib` has changed for `github.com/aleics/lib` that is on the repo name `gmusicgo`. What do you think? It is good like this?
Thanks for the feedback!

**Comment by THUNDERGROOVE** [comment]
This setup still isn't `go get`able which is pretty huge.  The imports need to be `github.com/aleics/gmusicgo/lib/...` isntead of the `github.com/aleics/lib/...`

The current setup makes it impossible to use your library in an idiomatic way.

**Comment by aleics** [comment]
I updated now the code. Can you take a look if now it's correct?
