### ISSUE TITLE
panic in lib/stream/stream.go

### ISSUE THREAD

**Issue by THUNDERGROOVE** [aleics/gmusicgo#2]
Hi.

In the method `Stream.StreamAudioRequest` there are a couple panics.

Generally, panics are used to indicate some kind of programmer error.

It seems much more idiomatic to return an error instead and let it fall down the call stack.  Additionally, the error from closing the connection can be safely ignored, which would make the flow of `StreamAudioRequest` feel less awkward.

If you would like, I could clean it up a bit?  I'd love to use this library, but it needs a bit of help.

**Comment by aleics** [comment]
Hi!

You can fork the repo and work with it as long as you want.
